# Generated by Django 5.2.7 on 2025-12-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        editable=False,
                        help_text="User's ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="User's First Name",
                        max_length=20,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="User's Last Name",
                        max_length=30,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="User's Preferred Reference",
                        max_length=30,
                        null=True,
                        verbose_name="Alias",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's Email Address",
                        max_length=60,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        help_text="User's Username",
                        max_length=30,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="User's Password",
                        max_length=256,
                        verbose_name="Password",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "created_on",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Account Created On",
                        verbose_name="Created On",
                    ),
                ),
                (
                    "updated_on",
                    models.DateField(
                        auto_now=True,
                        help_text="Account Updated On",
                        verbose_name="Updated On",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="User's Profile Picture",
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                        verbose_name="Site Theme",
                    ),
                ),
                (
                    "display_name_preference",
                    models.CharField(
                        choices=[
                            ("full", "Full Name (e.g., John Doe)"),
                            ("username", "Username (e.g., johndoe123)"),
                            ("alias", "Alias (e.g., Johnny)"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="Display Name Preference",
                    ),
                ),
            ],
        ),
    ]
