# Generated by Django 5.2.7 on 2025-12-11 23:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_id",
                    models.AutoField(
                        editable=False,
                        help_text="Project ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Project ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="Name Of Project",
                        max_length=100,
                        verbose_name="Project Name",
                    ),
                ),
                (
                    "project_desc",
                    models.TextField(
                        blank=True,
                        help_text="Description Of Project",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Project Start Date",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Project End Date",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date User Joined Project",
                        verbose_name="Joined Date",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Manager", "Manager"), ("Member", "Member")],
                        default="Member",
                        help_text="Users role in this member",
                        max_length=7,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.ProjectMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.AutoField(
                        editable=False,
                        help_text="Task ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Task ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("To Do", "Todo"),
                            ("In Progress", "Inprogress"),
                            ("Testing", "Testing"),
                            ("Done", "Done"),
                        ],
                        help_text="Task Status",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name Of Task",
                        max_length=100,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "task_desc",
                    models.TextField(
                        blank=True,
                        help_text="Description Of Task",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Task Due Date",
                        null=True,
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_assigned",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date User Assigned To Task",
                        verbose_name="Date Assigned",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "user")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                related_name="tasks",
                through="projects.TaskAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
