# Generated by Django 5.2.7 on 2025-12-11 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "org_id",
                    models.AutoField(
                        editable=False,
                        help_text="Organization's ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Org ID",
                    ),
                ),
                (
                    "org_name",
                    models.CharField(
                        help_text="Organization Name",
                        max_length=30,
                        verbose_name="Organization Name",
                    ),
                ),
                (
                    "org_code",
                    models.CharField(
                        help_text="Private Code For Connecting To Organization",
                        max_length=256,
                        unique=True,
                        verbose_name="Organization Code",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description Of Organization",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_on",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Organization Creation Date",
                        verbose_name="Created On",
                    ),
                ),
                (
                    "org_creator",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Member", "Member"), ("Manager", "Manager")],
                        default="Member",
                        help_text="Role Of User",
                        max_length=7,
                        verbose_name="Role",
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date User Joined Organization",
                        verbose_name="Joined Date",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organization.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                related_name="organizations",
                through="organization.OrganizationMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
